### ISSUE TITLE
sagan fails to start

### ISSUE THREAD

**Issue by Haxx** [quadrantsec/sagan#17]
Hi,

I have just installed **sagan(1.2.2-1)** on **Arch Linux(5.10.56-1-lts)** , no install errors to report, but as I am
going through the **"Post-installation setup and testing"** section from the **Sagan User guide(readthedocs)**:
 - _**"To test, run sagan --debug syslog,engine as the root user. It will switch to the sagan user when ready, and
    remain running in the foreground.**_
**command**: $ sudo sagan --debug syslog,engine
output:**sagan: error while loading shared libraries: libesmtp.so.6: cannot open shared object file: No such file or directory**
**issue**: sagan fails to start
**libesmtp version**: community/libesmtp 1.1.0-1 [installed]

**libesmtp Directories**:
libesmtp /usr/include/auth-client.h
libesmtp /usr/include/libesmtp.h
libesmtp /usr/lib/
libesmtp /usr/lib/esmtp-plugins-6.2.0/
libesmtp /usr/lib/esmtp-plugins-6.2.0/sasl-crammd5.so
libesmtp /usr/lib/esmtp-plugins-6.2.0/sasl-login.so
libesmtp /usr/lib/esmtp-plugins-6.2.0/sasl-ntlm.so
libesmtp /usr/lib/esmtp-plugins-6.2.0/sasl-plain.so
libesmtp /usr/lib/libesmtp.so
libesmtp /usr/lib/libesmtp.so.6.2.0

At first sight it looks like sagan cannot find libesmtp.so.6 library. 
Do you have any suggestion?

Thanks,

**Comment by J-Beavers** [comment]
Did you run the command as root, or sudo?

**Comment by beave** [comment]
bump...

**Comment by quadrantsec** [comment]
Closing ... no response from person who submitted the ticket.
