### ISSUE TITLE
[sagan-users] SEGV version 2.0.0

### ISSUE THREAD

**Issue by beave** [quadrantsec/sagan#2]
Hello all,

Today I tried updating to version 2.0.0 from the new github repo.

If I start sagan from the shell it is starting up OK, but as soon as it starts sagan as daemon with systemctl start sagan I get a failure (signal=SEGV).

If I revert to earlier versions in the old repo I can get commit c9c22a5ea0882b5954e8dba94dcbf533a75cd0c1 from 26-10 running, but commit 43cd81adafdf6686584d40e8d1bc64fb120ddba6 from 28-10 gives me the same SEGV message as the most recent version.

I'm wondering if someone has also encountered the same issue and knows a solution.

The OS I'm running on is OS 18.04LTS and I have the core dump attached to this message.

Best regards,

Stef
[stacktrace.txt](https://github.com/quadrantsec/sagan/files/5837309/stacktrace.txt)

**Comment by smr1983** [comment]
I think I found the issue, but I haven't found the reason why it wasn't giving issues when not starting as a daemon. So that is still bothering me.

Best regards,

Stef

**Comment by beave** [comment]
Yeah.  I can replicate it.  I'm just trying to determine the issue.

**Comment by beave** [comment]
Merged PR3 to fix this.

I wonder if the non-daemon mode not starting is related to testing the tty? 

https://github.com/quadrantsec/sagan/blob/main/src/sagan.c#L354-L367

**Comment by quadrantsec** [comment]
I'm going to close this.  It appears to be fixed in my testing.  Please let reopen if the issue comes up again. Thank you!
