### ISSUE TITLE
External output plugin produces invalid JSON

### ISSUE THREAD

**Issue by wokis** [quadrantsec/sagan#21]
The external output plugin sends JSON with a dangling `normalize` making the entire JSON sent invalid.

Looks like https://github.com/quadrantsec/sagan/blob/d264dc3081715d7f360740fd53fded5de2ed7ff1/src/output-plugins/external.c#L192 might be at fault. I'm unsure though if `Event->json_normalize` should be true for rules not using the `normalize;` keyword.

```
{ "signature_id": 505234, "signature": "Authentication failure", "rev": 1, "severity": 1, "category": "unsuccessful-user", "priority": 1, "timestamp": "01-07-2022 12:32:21.859190", "drop": "false", "flow_id": 852827190, "in_iface": "", "src_ip": "192.168.10.33", "src_port": 514, "dest_ip": "192.168.10.33", "dest_port": 514, "xff": "192.168.10.33", "proto": "UDP", "syslog_facility": "local7", "syslog_level": "info", "syslog_priority": "info", "syslog_message": "[2022\/01\/07 12:32:15.228367,  3] ..\/..\/source4\/auth\/kerberos\/krb5_init_context.c:80(smb_krb5_debug_wrapper)#012  Kerberos: Failed to decrypt PA-DATA -- user1@DOMAIN1 (enctype aes256-cts-hmac-sha1-96) error Decrypt integrity check failed for checksum type hmac-sha1-96-aes256, key type aes256-cts-hmac-sha1-96#", "normalize":  }
```
```
alert any $EXTERNAL_NET any -> $HOME_NET any (msg: "Authentication failure"; content:"Kerberos: Failed to decrypt PA-DATA -- "; program: samba; classtype: unsuccessful-user; sid: 505234; rev: 1; external: /usr/local/sagan/external.py)
```

**Comment by beave** [comment]
Doh!  I'll take a look at this over the weekend.   Thanks!

**Comment by beave** [comment]
I looked at this for a bit and need to look a little more.  I don't like the fact that I am creating some "new" JSON for external when I should be using the already generated JSON for the alert data.   I think you are correct that the snprintf() call is not generating the normalize data correctly.   I'm probably going to rework this code to use the "alert" JSON that's already in memory!

Also, about "normalize" key itself.  If there is any signature in your rules that has a "normalize" keyword,  then the normalize  JSON will be added regardless of if the signature fired had "normalize" or not.  Originally,  we would just "throw away" the normalization data,  which doesn't make sense.  If we've normalized the data for some other signature,  we might as well keep that data and record it even if the signature firing doesn't need it.

Hopefully this makes sense.

**Comment by beave** [comment]
Okay!  The JSON that external uses is the same as the EVE file output.  This makes things more unified and should resolve this issue.  Please let me know if it does not.   You may need to adjust your script since Sagan uses EVE output for external now.  

Let me know how it works out!

**Comment by quadrantsec** [comment]
I am not sure I understand.   The "category" and "classtype" are pulled from the reference file.   For example,  The "category" of "Detection of a Network Scan" would have a classtype of "network-scan" with a "severity" of 3.  

Here's the line from the reference.conf

config classification: network-scan,Detection of a Network Scan,3

That appears to be everything.  Am I missing something?

**Comment by wokis** [comment]
Following your example, the classtype "network-scan" isn't available in the returned JSON data, only the category "Detection of a Network Scan " is returned.

**Comment by quadrantsec** [comment]
I see what you mean. 

I must have mistaken the "alert.rule" 'classtype' for the EVE having the 'classtype'.  My mistake.

I like to keep the EVE as similar to the Suricata EVE as possible.  That being said,  adding the key/value wouldn't "break" anything.   I'll make this a sagan.yaml argument.

That shouldn't take long.  I'll let you know when its done!

**Comment by wokis** [comment]
Any news on this one?

**Comment by quadrantsec** [comment]
This now uses the same JSON that the engine uses internally.  Please re-open if this is still an issue.

**Comment by wokis** [comment]
I can't see that the key/value we talked about in January was added. Latest git master produces the same JSON output as before with the key/value missing.
