### ISSUE TITLE
json_pcre { } range error

### ISSUE THREAD

**Issue by bryant-smith** [quadrantsec/sagan#39]
Example:
`json_pcre:".QuestionName", "/^.*\w{1,50}\.(\w+\.\w{2,10})$/";`

In the above example if you use `{1,50}` sagan will error with `[rules.c, line 2354] Missing last '/' in json_pcre`.  This doesn't affect the normal `pcre` keyword.  Also, single digits `{50}` work just fine but if a range is specified the error will occur.

**Comment by quadrantsec** [comment]
I see this issue on this.  It is a internal parsing issue.  I'll have to figure out a work around.
