### ISSUE TITLE
Sagan loads rules with "threshold" written incorrectly

### ISSUE THREAD

**Issue by wrharding** [quadrantsec/sagan#48]
## Observed behavior

Two rules in the https://github.com/quadrantsec/sagan-rules repo are written incorrect, possibly in an older format:

```
alert any $EXTERNAL_NET any -> $HOME_NET any (msg:"[ASTERISK] Login session failed [0/5]"; content: "Wrong password"; classtype: unsuccessful-user; program: asterisk; reference: url,wiki.quadrantsec.com/bin/view/Main/5000179; threshold:suppress, track by_src, count 5, seconds 900; sid:5000179; rev:4;)

alert any $EXTERNAL_NET any -> $HOME_NET any (msg:"[ASTERISK] Brute force login session failed [5/5]"; content: "Wrong password"; xbits: set, brute_force ,track ip_src, expire 21600; classtype: brute-force; program: asterisk; reference: url,wiki.quadrantsec.com/bin/view/Main/5002942; after: track by_src, count 5, seconds 300; threshold:suppress, track by_src, count 5, seconds 900; sid:5002942; rev:4;)
```

Sagan successfully runs when loading in these rules, but the thresholds are not applied properly. This results in no threshold being applied. Changing to the documented way of `threshold: type suppress, ...` enables the rule to perform as expected.

## Expected behavior

Sagan fails to load due to the rule being written incorrectly

## Sagan version and OS version
Sagan v2.1.0
Debian 11

**Comment by quadrantsec** [comment]
Thanks!  This has been resolved for both "threshold" and "after".  It now does better sanity checks when loading.
