### ISSUE TITLE
fails to build with GCC 10: multiple definitions of the same variable

### ISSUE THREAD

**Issue by jonassmedegaard** [quadrantsec/sagan#6]
As documented at https://gcc.gnu.org/gcc-10/porting_to.html GCC 10 defaults to `-fno-common` which reveals issues with the code in sagan.

See https://bugs.debian.org/957771 for more details.

Workaround is to build with `fcommon` but better would be to cleanup the code.

**Comment by quadrantsec** [comment]
Hello Jonas, 

 I think I resolved all the GCC 10 compile time issues.    I also took sometime to clean up the compile time warnings as well.

**Comment by jonassmedegaard** [comment]
Quoting Quadrant Information Security (2021-01-26 21:06:07)
>  I think I resolved all the GCC 10 compile time issues.    I also took sometime to clean up the compile time warnings as well.   

great!

Unless something else is stopping that, it would be helpful if you then make a formal release with these nice improvements: Debian is entering "deep freeze" in few weeks, and it would be quite nice to have an offcial 2.x release into Debian before that.

**Comment by quadrantsec** [comment]
I agree! 

I went to tag/release that commit and it's now to far back.   Basically, it doesn't show up in the pull down menu :(   The menu appears to only go back 7 days.   I was already planning on a 2.0.1 release pretty soon due to a --daemon segfault that was reported.   I can probably push up testing time if that would help?  If not,  I can see what I can do about getting a older commit as a release.

**Comment by quadrantsec** [comment]
P.S  - I'm sure there's a way to do it.... I just need to research....

**Comment by jonassmedegaard** [comment]
Quoting Quadrant Information Security (2021-01-26 21:32:14)
> I went to tag/release that commit and it's now to far back.   Basically, it doesn't show up in the pull down menu :(   The menu appears to only go back 7 days.   I was already planning on a 2.0.1 release pretty soon due to a --daemon segfault that was reported.   I can probably push up testing time if that would help?  If not,  I can see what I can do about getting a older commit as a release.

Sorry, I don't know what it is you are looking for in a pull down menu.

(I don't use Github for code myself - only contribute comments in issue trackers and use plain git elsewhere for code)

What I meant was simply "git tag" and then "git push --tags"

**Comment by quadrantsec** [comment]
Oh.  Okay - It's been tagged.  I was attempting to do it through Github. 

I think we're good on GCC 10.  Let me know if you see any more issues.  I suspect I'll have Sagan 2.0.1 out later this week.  I'll make sure it's tagged and all that good stuff :)

**Comment by beave** [comment]
I'm going to close this.    I've tested multiple times on with GCC 10.  please let me know if this is not the case!

**Comment by jonassmedegaard** [comment]
oh, sorry that I didn't make myself clear: Yes, I agree that your fix solves this issue.
