### ISSUE TITLE
Report issue on error in signature

### ISSUE THREAD

**Issue by MigNov** [quadrantsec/sagan#65]
Hi Sagan developers,
recently I've encountered the issue that Sagan does not report error on invalid signature and there's no error in the output/log file. For example in signature like:
``
alert any any any -> any any (msg:"VPN User Login";content:"logged in" content:"ovpn"; priority:2; program:vpn; classtype:information; sid:4800000014; rev:1;)
``
as it's missing the semicolon between content:"logged in" and content:"ovpn" however it's easy to overlook it. It would be nice if Sagan could report it some reasonable way, e.g. "[INVALID_SIGNATURE] Signature 4800000014 has invalid field: content".

Would it be possible to implement such an approach?

Thanks,
Michal

**Comment by quadrantsec** [comment]
Hello Michal !

What version of Sagan are you using?  We're getting close to release 2.1.0 which does more sanity checks of the signatures.   If you're not using 2.1.0 (git master),  could you load that up and see if it throws an error?  It should.  

Thank you!

**Comment by MigNov** [comment]
Hello,
I have tried using the latest Sagan master and the situation it the same - the dropped counter is increased but no information that the signature is invalid.

The rules file I've used is:

```
alert any $EXTERNAL_NET any -> $HOME_NET any (msg: "test signature 1"; classtype: bad-unknown; sid: 5000156; rev:1;)
alert any any any -> any any (msg: "test signature 2"; classtype: bad-unknown; sid: 5000157; rev:1;)
alert any any any -> any any (msg: "test signature 3"; content:"logged in" content:"ovpn"; classtype: bad-unknown; sid:5000158; rev:1;)
```

Error is in 5000158 as there's missing semicolon between those two content keywords. Could you please verify?

Thanks,
Michal

**Comment by quadrantsec** [comment]
A fix for this has been pushed.  Thanks again for reporting it!
