### ISSUE TITLE
hex values in meta_content and json_meta_content

### ISSUE THREAD

**Issue by bryant-smith** [quadrantsec/sagan#68]
I've tested with both meta_content and json_meta_content using `|20|` to account for spaces but couldn't get it to generate an alert properly.

Below is a simplified version of the rule I was working on.  If logs are needed I can provide those.

`
alert any $HOME_NET any -> $EXTERNAL_NET any (msg: "[MSAPI-SECURITYCOMPLIANCECENTER] Alert Entity Generated (CATCHALL RULE)"; program:SecurityComplianceCenter; json_meta_content:".Name",removed|20|after; json_meta_contains; classtype: suspicious-traffic; sid:5; rev:1;)
`

**Comment by OGSteve** [comment]
Also confirmed this issue.

**Comment by quadrantsec** [comment]
I was able to replicate.  In both functions,  there was a premature call to the "Remove_Spaces" function.   Basically, "Content_Pipe" would be called, which would convert |20| to a space.  Then next line,  was "Remove_Spaces".  Swapped that around and now seems to be fine.
