### ISSUE TITLE
after keyword and track by_string

### ISSUE THREAD

**Issue by bryant-smith** [quadrantsec/sagan#69]
`Sagan version 2.1.0`

When trying to use `after: track by_string, count 1, seconds 300;` in a rule, I ran into the below error.  If it's changed to `by_username` it works correctly.

`[E] [rules.c, line 3495] 'after' keyword appears to be invalid at line 19 in update.rules. Abort`

**Comment by quadrantsec** [comment]
This should be fixed!  Thanks!
