### ISSUE TITLE
source tarball is dirty

### ISSUE THREAD

**Issue by jonassmedegaard** [quadrantsec/sagan#7]
Source tarball for release 2.0.0 contains the following files which should instead be git-ignored:
config.h.in~
autom4te.cache/*

**Comment by quadrantsec** [comment]
Thank you Jonas.  This is a huge help.  I'll start cleaning this up along with other tickets ASAP.

**Comment by quadrantsec** [comment]
Jonas, 

There's been several fixes and updates.  I'm going to slate this for a 2.0.1 release, which I'll take in git  & clean up the tarball.  I'm going to test out in the field until next week to make sure no new bugs/faults have been introduced.
