### ISSUE TITLE
Distance & Within are not working with meta_content

### ISSUE THREAD

**Issue by OGSteve** [quadrantsec/sagan#70]
Distance and Within are not functioning as intended.

-works with just depth, does not work with depth+meta_content+distance
-works with depth+content: content:"A service"; depth:18;content:"ADMIN$";distance:130;

Discovered during review of rule:

alert any $HOME_NET any -> $HOME_NET any (msg:"[WINDOWS-POWERSHELL] Suspicious FromBase64String Encoded Commands"; program: *PowerShell*; event_id:400,800,4103,4104; content:"FromBase64String"; meta_content:"%sagan%",JAB,TVq,SUVY,SQBFAF,SQBuAH,aWV4,aQBlA,Y21k,Qzpc,Yzpc,UEs; within:100; reference:url,gist.github.com/Neo23x0/6af876ee72b51676c82a2db8d2cd3639; classtype:suspicious-command; sid:5007143; rev:1;)

Tested further with rule:

alert any $EXTERNAL_NET any -> $HOME_NET any (msg: "[WINDOWS-MISC] A service was installed in the system with suspicious programs"; json_map:"message",".Message"; json_map:"event_id",".EventID"; event_id:7045,4697; content:!"\Microsoft\"; nocase; meta_content:"%sagan%",ADMIN$,C$,IPC$,cmd|20 2f|c,powershell,pwsh,comspec,screenconnect,SystemDrive,teamviewer,psexesvc,psexec,rundll32.exe,regsvr32.exe,cscript.exe,regsvcs.exe,wmic.exe,anydesk,logmein,ultravnc; meta_nocase; classtype: suspicious-traffic; program:*Security*; reference: url,learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4697; reference:url,www.socinvestigation.com/hunting-for-suspicious-windows-services-mind-map/; sid:5013683; rev:1;)

Separate but related, distance does not work by itself and requires depth. It would be beneficial to tell sagan "ignore 50 bytes before looking for this content" without having to use depth prior.

**Comment by quadrantsec** [comment]
Try with the special keywords:

https://sagan.readthedocs.io/en/latest/rule-keywords.html#meta-within
