### ISSUE TITLE
Protocol-map.c error

### ISSUE THREAD

**Issue by ToniYap** [quadrantsec/sagan#71]
Hi all, I face this problem when I try to compile sagan, Kindly please help me. Thank you
user@ubuntu-Virtual-Machine:~$ sudo sagan --debug syslog,engine
[sudo] password for user:
[] Sagan's PID is 4985
[] Loading classifications.conf file. [/usr/local/etc/sagan-rules/classification.config]
[] 53 classifications loaded
[] Loading references.conf file. [/usr/local/etc/sagan-rules/reference.config]
[] 6 references loaded.
[] Loading protocol map file. [/usr/local/etc/sagan-rules/protocol.map]
[E] [protocol-map.c, line 104] 'type' not specified at line 2

Sagan version 2.0.2

**Comment by quadrantsec** [comment]
Hello and sorry for the delay.

With Sagan 2.0.2,  you'll want to use the compatible signatures. Those are at: 

https://rules.quadrantsec.com/sagan-rules-20211230.tar.gz

Another option is to load Sagan from Github and use the signatures from Github.  Hopefully this helps. I'm going to close this out but if you have more questions,  please re-open.
