### ISSUE TITLE
A mistake when checking an IP is valid or not

### ISSUE THREAD

**Issue by UET-HDCien** [quadrantsec/sagan#75]
![ipv6](https://github.com/quadrantsec/sagan/assets/35697779/e9d312c4-3b6e-40fb-8018-2723167484bd)
File: util.c, Line: 1202 should change from ver = 4 to ver == 4 to avoid a mistake when checking whether an IPv6 is valid or not

**Comment by quadrantsec** [comment]
Nice catch!  I'll fix this ASAP!

**Comment by quadrantsec** [comment]
Thank you.  Fixed!
