### ISSUE TITLE
Event_id - detection doesn't work

### ISSUE THREAD

**Issue by iku899** [quadrantsec/sagan#8]
Hallo,
I am using Sagan's JSON input module but I pull the event ID from the message rather than from a JSON field.
The event_id is at the beggining of the message field.
In version 2.0.1 the event_id field is UNDEFINE.
After the patch ( https://groups.google.com/g/sagan-users/c/ju-3g2vIYgE  ) the result is that event_id is empty string.

Best Regards
Ivan

-----

[D] Data in _Sagan_Proc_Syslog (including extracted JSON)
[D] -----------------------------------------------------------------------------
[D]  * message: "  4727: A security-enabled global group was created. Subject: Security ID: S-1-5-21-3641769155-4107095991-1524253519-8107 Account Name: USER Account Domain: DOMAIN Logon ID: 0x4DCCB98 New Group: Security ID: S-1-5-21-3641769155-4107095991-1524253519-31261 Group Name: dddddd Group Domain: DOMAIN Attributes: SAM Account Name: dddddd SID History: - Additional Information: Privileges: -"
[D]  * program: "Security"
[D]  * host: "10.XXX.XXX.XX"
[D]  * level: "info"
[D]  * facility: "user"
[D]  * priority: "14"
[D]  * tag: "UNDEFINED"
[D]  * time: "20:51:58"
[D]  * date: "2021-01-28"
[D]  * src_ip : ""
[D]  * dst_ip : ""
[D]  * src_port : "0"
[D]  * dst_port : "0"
[D]  * proto : "0"
[D]  * ja3: ""
[D]  * event_id: ""
[D]  * md5: ""
[D]  * sha1: ""
[D]  * sha256: ""
[D]  * filename: ""
[D]  * hostname: ""
[D]  * url: ""
[D]  * username: ""

**Comment by beave** [comment]
You won't see it with --debug json because Sagan isn't extracting the value from JSON.  It's extracting the event ID from the "message",  using more traditional means (event_id.c).  Run it with "--debug engine" and you should see it.

[D] [processors/engine.c, line 1494] **[Trigger]*********************************
[D] [processors/engine.c, line 1495] Program: Security | Facility: auth | Priority: info | Level: UNDEFINED | Tag: UNDEFINED | **_Event ID : 4727_**
[D] [processors/engine.c, line 1496] Threshold flag: 0 | After flag: 0 | Flexbit Flag: 0 | Flexbit status: 0
[D] [processors/engine.c, line 1497] Triggering Message:  4727: A security-enabled global group was created. Subject: Security ID: S-1-
5-21-3641769155-4107095991-1524253519-8107 Account Name: admXX Account Domain: COMPANY Logon ID: 0x4DCCB98 New Group: Security ID: S-1-
5-21-3641769155-4107095991-1524253519-31254 Group Name: testGROUP Group Domain: COMPANY Attributes: SAM Account Name: testGROUP SID His
tory: - Additional Information: Privileges: -

**Comment by iku899** [comment]
Is there any condition for running: sagan --debug engine ?
Because I run it like this and I see

 Received/Processed/Ignored : 1/1/0 (100.000%/0.000%)
[*]   /   \/)  Signatures matched         : 0 (0.000%)
[*]            Bytes Processed            : 591
[*]  (|| ||)   Alerts                     : 0 (0.000%)

but I don't see anything more.
Before I run:  sagan --debug json,engine

**Comment by iku899** [comment]
sagan --debug syslog,engine

[D] [sagan.c, line 1217] [batch position 0] Raw log: {"fromhost-ip":"10.XXX.XXX.XXX","syslogfacility-text":"user","pri":"14","syslogseverity-text":"info","syslogtag":"Security[560]:","date":"2021-01-28","time":"21:45:12","programname":"Security","msg":" 4727: A security-enabled global group was created. Subject: Security ID: S-1-5-21-3641769155-4107095991-1524253519-8107 Account Name: admku Account Domain: XXXXX Logon ID: 0x4DCCB98 New Group: Security ID: S-1-5-21-3641769155-4107095991-1524253519-31264 Group Name: sasasa Group Domain: XXXXX Attributes: SAM Account Name: sasasa SID History: - Additional Information: Privileges: -"}

[D] [processor.c, line 137] [batch position 0] Raw log: {"fromhost-ip":"10.XXX.XXX.XXX","syslogfacility-text":"user","pri":"14","syslogseverity-text":"info","syslogtag":"Security[560]:","date":"2021-01-28","time":"21:45:12","programname":"Security","msg":" 4727: A security-enabled global group was created. Subject: Security ID: S-1-5-21-3641769155-4107095991-1524253519-8107 Account Name: admku Account Domain: XXXXX Logon ID: 0x4DCCB98 New Group: Security ID: S-1-5-21-3641769155-4107095991-1524253519-31264 Group Name: sasasa Group Domain: XXXXXX Attributes: SAM Account Name: sasasa SID History: - Additional Information: Privileges: -"}

[D] [processor.c, line 169] **[Parsed Syslog]*********************************
[D] [processor.c, line 170] Host: 10.XXX.XXX.XXX | Program: Security | Facility: user | Priority: 14 | Level: info | Tag: UNDEFINED | Date: 2021-01-28 | Time: 21:45:12
[D] [processor.c, line 171] Parsed message:   4727: A security-enabled global group was created. Subject: Security ID: S-1-5-21-3641769155-4107095991-1524253519-8107 Account Name: admku Account Domain: XXXXXX Logon ID: 0x4DCCB98 New Group: Security ID: S-1-5-21-3641769155-4107095991-1524253519-31264 Group Name: sasasa Group Domain: XXXXXX Attributes: SAM Account Name: sasasa SID History: - Additional Information: Privileges: -

**Comment by quadrantsec** [comment]
Can you send me a copy of your signature your trying to trigger?  Thanks.

**Comment by quadrantsec** [comment]
The "Parsed Syslog" is after JSON parsing but before the engine.

You'll only see the event_id if the signature is successfully matched.  That is,  all conditions (including the event id, content, pcre,  etc) are matched. 

I want to test with the log message and the signature.   I was getting it to trigger but with my own very simple signature.  If it's a stock rule,  the signature ID will work.

**Comment by iku899** [comment]
It is a stock signature
alert any $EXTERNAL_NET any -> $HOME_NET any (msg: "[WINDOWS-AUTH] Security enabled group created"; event_id: 4754,4731,4727,658,635,631; classtype: system-event; program: *Security*; reference: url,wiki.qu
adrantsec.com/bin/view/Main/5001162; sid: 5001162; rev:8;)

**Comment by quadrantsec** [comment]
Cool.. I'll test it ASAP.

**Comment by quadrantsec** [comment]
Here's the signature I'm using:

**alert any $EXTERNAL_NET any -> $HOME_NET any (msg: "[WINDOWS-AUTH] Security enabled group created"; event_id: 4754,4731,4727,658,635,631; classtype: system-event; program: *Security*; reference: url,wiki.quadrantsec.com/bin/view/Main/5001162; sid: 5001162; rev:8;)**

This is my test JSON I'm feeding into Sagan for testing:

**{"TAGS":".source.s_src","SOURCEIP":"127.0.0.1","SOURCE":"s_src","SEQNUM":"4","PROGRAM":"Security","PRIORITY":"info","PID":"25130","MESSAGE":"4727: A security-enabled global group was created. Subject: Security ID: S-1-5-21-3641769155-4107095991-1524253519-8107 Account Name: admXX Account Domain: COMPANY Logon ID: 0x4DCCB98 New Group: Security ID: S-1-5-21-3641769155-4107095991-1524253519-31254 Group Name: testGROUP Group Domain: COMPANY Attributes: SAM Account Name: testGROUP SID History: - Additional Information: Privileges: -","LEGACY_MSGHDR":"sshd[25130]: ","HOST_FROM":"dev-2","HOST":"dev-2","FACILITY":"auth","DATE":"Jan 28 16:33:15"}**

I'm starting Sagan with --debug engine in a screen.  In a separate screen, I'm piping the JSON into Sagan's FIFO like this:

**cat /tmp/hold.json > /var/sagan/test.fifo   #  hold.json is the JSON above**

I get the resulting output from Sagan:

**[D] [processors/engine.c, line 1494] **[Trigger]*********************************
[D] [processors/engine.c, line 1495] Program: Security | Facility: auth | Priority: info | Level: UNDEFINED |
 Tag: UNDEFINED | Event ID: 4727
[D] [processors/engine.c, line 1496] Threshold flag: 0 | After flag: 0 | Flexbit Flag: 0 | Flexbit status: 0
[D] [processors/engine.c, line 1497] Triggering Message:  4727: A security-enabled global group was created. 
Subject: Security ID: S-1-5-21-3641769155-4107095991-1524253519-8107 Account Name: admXX Account Domain: COMPANY Logon ID: 0x4DCCB98 New Group: Security ID: S-1-5-21-3641769155-4107095991-1524253519-31254 Group Name: testGROUP Group Domain: COMPANY Attributes: SAM Account Name: testGROUP SID History: -Additional Information: Privileges: -**

Note: It will only display the event ID upon match. 

I hope this helps.

**Comment by quadrantsec** [comment]
Okay - Re-pull and try this.  I think this might resolve it.  Let me know.  Thanks.

**Comment by iku899** [comment]
It is solved! Thank you for great work.

Best Regards
Ivan
