### ISSUE TITLE
Sagan YAML parser checks for required variables before configuration parsing is complete

### ISSUE THREAD

**Issue by chrisspankroy** [quadrantsec/sagan#83]
Hello,

I've recently tried to separate out the main `sagan.yaml` file into multiple smaller files for ease of automating updates to the configuration. For example, below is the configuration I pass to Sagan on startup:

```
%YAML 1.1
---

#  ,-._,-.  Sagan configuration file [http://sagan.quadrantsec.com]
#  \/)"(\/  Champ Clark III & The Quadrant Infosec Team: http://quadrantsec.com
#   (_o_)   Copyright (C) 2009-2019 Quadrant Information Security., et al.
#   /   \/)
#  (|| ||)
#   oo-oo

include: "01-vars.yaml"
include: "02-core.yaml"
include: "03-processors.yaml"
include: "04-outputs.yaml"
include: "05-rules.yaml"
```

where `01-vars.yaml` contains the `vars` section of the configuration, `02-core.yaml` contains the `core` section, and so on. 

The issue is that once `libyaml` gets to the end of parsing the first included file `01-vars.yaml`, the `Load_YAML_Config` function tries to perform some sanity checks on the configuration since it thinks the entire configuration has been loaded. This assumption is true when only using one YAML file, but is premature in this context since only one section of the configuration has been loaded. This causes Sagan to error out with errors like 
```
[E] [01/17/2024 14:17:31] - [config-yaml.c, line 2774] The 'sagan_host' option was not found and is required.
```
since `02-core.yaml` has not yet been loaded. These sanity checks should only be run once the entire configuration has been loaded.

**Comment by beave** [comment]
Merged!  Thank you
